// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAHrpUQdvDL_zuESf590hniBe7KH3Jjbo',
    appId: '1:45384405446:web:8e66cae92385fa21aa62c7',
    messagingSenderId: '45384405446',
    projectId: 'foolo-97c24',
    authDomain: 'foolo-97c24.firebaseapp.com',
    storageBucket: 'foolo-97c24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPTtcckZ8FKJsWZT5pRDvbkLHmN8Xw8Fk',
    appId: '1:45384405446:android:44a9d96878dc169daa62c7',
    messagingSenderId: '45384405446',
    projectId: 'foolo-97c24',
    storageBucket: 'foolo-97c24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlw8Pd6vO-pExBGzKcn3DIntX5sH975Qw',
    appId: '1:45384405446:ios:6b7740543df0bebfaa62c7',
    messagingSenderId: '45384405446',
    projectId: 'foolo-97c24',
    storageBucket: 'foolo-97c24.firebasestorage.app',
    iosBundleId: 'com.example.amazonClone',
  );
}
