on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"
jobs:
  build:
    name: Build & Release
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set JAVA_HOME
        run: echo "JAVA_HOME=$(/usr/libexec/java_home -v 17)" >> $GITHUB_ENV

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Setup Gradle
        run: gradle --version

      - name: Upgrade Gradle
        run: ./gradlew wrapper --gradle-version 8.1

      - name: Clean & Get Dependencies
        run: |
          flutter clean
          flutter pub get

      - name: Build APK
        run: flutter build apk --release

      - name: Push to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/apk/release/app-release.apk"
          tag: v1.0.${{ github.run_number }}
          token: ${{ secrets.TOKEN }}
